//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::managers::Entity as Managers;
pub use super::projects::Entity as Projects;
pub use super::time_entries::Entity as TimeEntries;
pub use super::users::Entity as Users;
