//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub job_number: i32,
    #[sea_orm(unique)]
    pub job_description: String,
    pub job_active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::time_entries::Entity")]
    TimeEntries,
}

impl Related<super::time_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
