//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Approved")]
    Approved,
    #[sea_orm(string_value = "Initial")]
    Initial,
    #[sea_orm(string_value = "Submitted")]
    Submitted,
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "work_codes")]
pub enum WorkCodes {
    #[sea_orm(string_value = "Checkout")]
    Checkout,
    #[sea_orm(string_value = "Meetings")]
    Meetings,
    #[sea_orm(string_value = "SoftwareDev")]
    SoftwareDev,
}
