//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manager_id: Option<i32>,
    #[sea_orm(unique)]
    pub name: String,
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::managers::Entity")]
    Managers,
    #[sea_orm(has_many = "super::time_entries::Entity")]
    TimeEntries,
}

impl Related<super::managers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Managers.def()
    }
}

impl Related<super::time_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
